<?php

namespace ContainerV1C6QbI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ss1EBZEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ss1EBZE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ss1EBZE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TaskController::createTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController::deleteTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController::editTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController::getTasks' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\TaskController:createTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController:deleteTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController:editTask' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'App\\Controller\\TaskController:getTasks' => ['privates', '.service_locator.K8mEeqr', 'get_ServiceLocator_K8mEeqrService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\TaskController::createTask' => '?',
            'App\\Controller\\TaskController::deleteTask' => '?',
            'App\\Controller\\TaskController::editTask' => '?',
            'App\\Controller\\TaskController::getTasks' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TaskController:createTask' => '?',
            'App\\Controller\\TaskController:deleteTask' => '?',
            'App\\Controller\\TaskController:editTask' => '?',
            'App\\Controller\\TaskController:getTasks' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
