version: '3.7'

services:
  php_gis_river_back:
    container_name: php_gis_river_back
    build: dockerfile/php
    restart: on-failure
    expose:
      - "9000"
    volumes:
      - ../app:/var/www/html
      - ../app/vendor:/var/www/html/vendor
    links:
      - mysql_gis_river_back

  nginx_gis_river_back:
    container_name: nginx_gis_river_back
    image: nginx:latest
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ../app:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - php_gis_river_back

  mysql_gis_river_back:
    container_name: mysql_gis_river_back
    image: mysql:5.7
    restart: on-failure
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
